global:
  scrape_interval: 15s
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100'] 
  - job_name: 'notification_service'
    static_configs:
      - targets: ['notification_service:8081'] 
  - job_name: 'my_microservice_1'
    static_configs:
      - targets: ['my_microservice_1:8080']  
  - job_name: 'my_microservice_2'
    static_configs:
    